#!/bin/bash
if [ "$1" == "-h" ] || [ "$1" == "--help" ]
then
    echo "git-stash-list v1.0"
    echo "
Lists each stash and its diff."
    echo ""
    echo "Usage:"
    echo "git stash-list"
    exit 0
fi

for y in `git stash list | cut -d":" -f1`
do
    echo $'\e[1;33m'$y$'\e[0m'
    git stash show $y
done

