#!/bin/bash
# todo: support using this without being in the root of the repo
if [ "$1" == "-h" ] || [ "$1" == "--help" ]
then
    echo "git-istage v1.0"
    echo "
Interactively stage files for committing."
    echo ""
    echo "Usage:"
	echo ""
    echo "$ git istage"
	echo ""
	echo "Then, for each prompt you may enter any of the following:"
	echo "    y, Y, 1, yes) Stage the file"
	echo "    n, N 0, no) Skip staging the file"
	echo "    d, D, diff) Get the diff for the file"
	echo "    x, X, e, E, q, Q, exit, quit) Quit"
    exit 0
fi

wait_for_answer()
{
	if [ $ALL -eq 1 ]
	then
		answer="y"
	else
		read -p "Do you want to stage $file? " answer
	fi

	case "$answer" in
		[yY1] | 'yes' )
			STAGE=1
			stage;;
		[nN0] | 'no' )
			echo "Skipping $file";;
		[aA] | 'all' )
			STAGE=1
			ALL=1
			stage;;
		[dD] | 'diff' )
			git diff $file
			wait_for_answer;;
		[eE] | 'edit' )
			$EDITOR $file
			wait_for_answer;;
		[xXqQ] | 'exit' | 'quit' )
			echo "Exiting";
			exit 0;;
		* )
			EXIT=1
			echo "Invalid response";
			exit 1;;
	esac
}

stage()
{
	if [ $STAGE -eq 1 ]
	then
		git add $file
	fi
}

FILES=`git diff --name-only`
ALL=0
EXIT=0
for file in $FILES
do
	STAGE=0
	wait_for_answer
done

exit $EXIT

