#!/bin/bash
if [ "$1" == "-h" ] || [ "$1" == "--help" ]
then
    echo "git-stash-list v1.2

Lists each stash and its diff.

Usage:

    git stash-list [INDEX]

    git stash-list --full [INDEX]
"
    exit 0
fi

if [ "$1" == "--full" ]
then
    # Thank you Mark Wilden's coworker Rich Fletcher at Rupter. And thank you
    # Mark Wilden for posting this tip:
    # http://blog.mwilden.com/2009/05/listing-contents-of-your-git-stash.html
    git show $(git stash list | cut -d":" -f 1)
elif [ ! -z $1 ]
then
    if [ ! -z $2 ]
    then
        if [ "$1" == "--full" ]
        then
            git show "stash@{$2}"
        else
            echo "Sorry, I couldn't understand you. What did you say?"
            sleep 1
            echo ""
            echo "Try,"
            echo "  $ git stash-list 1"
            exit 1
        fi
    else
        echo $'\e[1;33m'"stash@{$1}"$'\e[0m'
        git stash show "stash@{$1}"
    fi
else
    stashes=`git stash list`
    while read -r stash; do
        id=`echo $stash | cut -d":" -f1`
        echo $'\e[1;33m'$stash$'\e[0m'
        git stash show $id
    done <<< "$stashes"
fi

